const FETCH_USER_MOVIES = "FETCH_USER_MOVIES";
const SET_USER_CONNECTED = "SET_USER_CONNECTED";
const SET_USER = "SET_USER";
const SET_LIGHT_MODE = "SET_LIGHT_MODE";
const REMOVE_USER_MOVIE = "REMOVE_USER_MOVIE";
const ADD_USER_MOVIE = "ADD_USER_MOVIE";

const SET_LANGUAGE = "SET_LANGUAGE";

const FETCH_USER_FRIENDS = "FETCH_USER_FRIENDS";
const ADD_USER_FRIEND = "ADD_USER_FRIEND";
const REMOVE_USER_FRIEND = "REMOVE_USER_FRIEND";

export {FETCH_USER_MOVIES, SET_USER_CONNECTED, SET_USER, SET_LIGHT_MODE, REMOVE_USER_MOVIE, ADD_USER_MOVIE, SET_LANGUAGE, FETCH_USER_FRIENDS, ADD_USER_FRIEND, REMOVE_USER_FRIEND};