const FETCH_USER_MOVIES = "FETCH_USER_MOVIES";
const SET_USER_CONNECTED = "SET_USER_CONNECTED";
const SET_USER = "SET_USER";
const SET_LIGHT_MODE = "SET_LIGHT_MODE";

export {FETCH_USER_MOVIES, SET_USER_CONNECTED, SET_USER, SET_LIGHT_MODE};