const FETCH_USER_MOVIES = "FETCH_USER_MOVIES";
const SET_USER_CONNECTED = "SET_USER_CONNECTED";
const SET_USER = "SET_USER";
const SET_LIGHT_MODE = "SET_LIGHT_MODE";
const REMOVE_USER_MOVIE = "REMOVE_USER_MOVIE";
const ADD_USER_MOVIE = "ADD_USER_MOVIE";

const SET_LANGUAGE = "SET_LANGUAGE";

export {FETCH_USER_MOVIES, SET_USER_CONNECTED, SET_USER, SET_LIGHT_MODE, REMOVE_USER_MOVIE, ADD_USER_MOVIE, SET_LANGUAGE};